// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.barbri.com/
// Generated: 2026-06-02T13:40:59.185Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#464f57' | '#000000' | '#ffffff' | '#212529' | '#2a5488' | '#001722' | '#235ba8' | '#ececec' | '#f2f7fc' | '#155724' | '#343a40' | '#cccccc' | '#869c9e' | '#2e2e2e';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Nunito' | 'Times' | 'Bitter' | 'Material Symbols Rounded' | 'babri-icons';
export type FontSizeToken   = never;
export type FontWeightToken = '300' | '400' | '500' | '200' | '600' | '700';

export type SpacingToken = '2px' | '15px' | '24px' | '28px' | '48px' | '58px' | '80px' | '100px' | '106px' | '180px';

export type RadiusToken = '1px' | '4px' | '8px' | '16px' | '50px' | '100px';

export type DurationToken = '150ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
